"""Initial security audit table

Revision ID: 549d9704c09f
Revises: 
Create Date: 2026-07-06 01:09:12.510603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549d9704c09f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the audit log entry'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Identifier of the user who submitted the prompt'),
    sa.Column('original_prompt', sa.Text(), nullable=False, comment='The original, unedited prompt submitted by the user'),
    sa.Column('sanitized_prompt', sa.Text(), nullable=True, comment='The sanitized version of the prompt, if PII or sensitive data was redacted'),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Calculated risk score indicating potential security or compliance violations'),
    sa.Column('pii_detected', sa.Boolean(), nullable=False, comment='Flag indicating if Personally Identifiable Information was found in the prompt'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the prompt was received and audited'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_audit_timestamp_desc', 'security_audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_security_audit_user_time_desc', 'security_audit_logs', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_audit_user_time_desc', table_name='security_audit_logs')
    op.drop_index('ix_security_audit_timestamp_desc', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    # ### end Alembic commands ###
